Repository smutel/terraform-provider-netbox, pull requests merged in 2021-09, with the labels that each got.

#63 feat: Add an option to initialize the client with the private key
  README.md
  docs/index.md
  netbox/provider.go
  netbox/util.go
Labels: enhancement

#68 chore(release): 2.0.0
  CHANGELOG.md
Labels: chore

#69 fix: Fix CI for release generation
  .github/workflows/release.yml
Labels: bug

#70 chore(release): 2.0.1
  CHANGELOG.md
  package.json
Labels: chore

#71 ci: Run go fmt through the CI
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: ci

#73 fix: Terraform crashes when ip address not affected to vm/device
  docs/data-sources/tenancy_tenant_group.md
  docs/index.md
  docs/resources/ipam_ip_addresses.md
  netbox/resource_netbox_ipam_ip_addresses.go
Labels: bug

#74 chore(release): 2.0.2
  CHANGELOG.md
  package.json
Labels: chore
