Repository smutel/terraform-provider-netbox, pull requests merged in 2021-01, with the labels that each got.

#35 feat: Add resource and data for IPAM aggregate
  README.md
  docs/data-sources/ipam_aggregate.md
  docs/resources/ipam_aggregate.md
  examples/main.tf
  netbox/data_netbox_ipam_aggregate.go
  netbox/provider.go
  netbox/resource_netbox_ipam_aggregate.go
Labels: enhancement

#39 ci: Update CI version and options
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: ci

#38 chore(release): 1.2.0
  CHANGELOG.md
  package.json
Labels: chore

#40 ci: Fix get tag
  .github/workflows/release.yml
Labels: ci

#41 fix: Workaround for weird terraform behavior to fix boolean custom_fields
  netbox/util.go
Labels: bug
