Repository smutel/terraform-provider-netbox, pull requests merged in 2022-09, with the labels that each got.

#134 feat: Add debug option to main()
  .vscode/launch.json
  README.md
  examples/resources/netbox_ipam_ip_addresses/resource.tf
  main.go
Labels: enhancement

#140 feat: Allow prefix and ip to be dynamically assigned
  examples/main.tf
  examples/resources/netbox_ipam_ip_addresses/resource.tf
  examples/resources/netbox_ipam_prefix/resource.tf
  main.go
  netbox/resource_netbox_ipam_ip_addresses.go
  netbox/resource_netbox_ipam_prefix.go
  netbox/util.go
Labels: enhancement

#146 chore(release): 5.1.0
  CHANGELOG.md
  package.json
Labels: chore

#147 fix: Prevent panic if vcpus is null
  netbox/resource_netbox_virtualization_vm.go
Labels: bug
