Repository smutel/terraform-provider-netbox, pull requests merged in 2022-01, with the labels that each got.

#91 fix: Store empty static String field as nil in TF state
  .github/workflows/pr.yml
  netbox/resource_netbox_ipam_aggregate.go
  netbox/resource_netbox_ipam_ip_addresses.go
  netbox/resource_netbox_ipam_prefix.go
  netbox/resource_netbox_ipam_service.go
  netbox/resource_netbox_ipam_vlan.go
  netbox/resource_netbox_tenancy_tenant.go
  netbox/resource_netbox_virtualization_interface.go
  netbox/resource_netbox_virtualization_vm.go
Labels: bug

#92 ci: Fix ci changelog
  .gitignore
  examples/main.tf
Labels: ci

#93 chore(release): 2.2.1
  CHANGELOG.md
  package.json
Labels: chore
