Repository smutel/terraform-provider-netbox, pull requests merged in 2022-11, with the labels that each got.

#154 feat: Add suppport for missing customfield types
  examples/exports/v3.2/netbox_RIRs.csv
  examples/exports/v3.2/netbox_cluster types.csv
  examples/exports/v3.2/netbox_clusters.csv
  examples/exports/v3.2/netbox_custom fields.csv
  examples/exports/v3.2/netbox_dcim_device roles.csv
  examples/exports/v3.2/netbox_dcim_platforms.csv
  examples/exports/v3.2/netbox_dcim_sites.csv
  examples/exports/v3.2/netbox_device roles.csv
  examples/exports/v3.2/netbox_extras_custom fields.csv
  examples/exports/v3.2/netbox_extras_tags.csv
  examples/exports/v3.2/netbox_ipam_RIRs.csv
  examples/exports/v3.2/netbox_ipam_roles.csv
  examples/exports/v3.2/netbox_platforms.csv
  examples/exports/v3.2/netbox_roles.csv
  examples/exports/v3.2/netbox_sites.csv
  examples/exports/v3.2/netbox_tags.csv
  examples/exports/v3.2/netbox_virtualization_cluster types.csv
  examples/exports/v3.2/netbox_virtualization_clusters.csv
  examples/main.tf
  examples/resources/netbox_ipam_aggregate/resource.tf
  examples/resources/netbox_ipam_ip_addresses/resource.tf
  examples/resources/netbox_ipam_ip_range/resource.tf
  examples/resources/netbox_ipam_prefix/resource.tf
  examples/resources/netbox_ipam_service/resource.tf
  examples/resources/netbox_ipam_vlan/resource.tf
  examples/resources/netbox_tenancy_contact/resource.tf
  examples/resources/netbox_tenancy_contact_group/resource.tf
  examples/resources/netbox_tenancy_contact_role/resource.tf
  examples/resources/netbox_tenancy_tenant/resource.tf
  examples/resources/netbox_virtualization_interface/resource.tf
  examples/resources/netbox_virtualization_vm/resource.tf
  netbox/resource_netbox_ipam_aggregate.go
  netbox/resource_netbox_ipam_ip_addresses.go
  netbox/resource_netbox_ipam_ip_range.go
  netbox/resource_netbox_ipam_prefix.go
  netbox/resource_netbox_ipam_service.go
  netbox/resource_netbox_ipam_vlan.go
  netbox/resource_netbox_tenancy_contact.go
  netbox/resource_netbox_tenancy_contact_group.go
  netbox/resource_netbox_tenancy_contact_role.go
  netbox/resource_netbox_tenancy_tenant.go
  netbox/resource_netbox_virtualization_interface.go
  netbox/resource_netbox_virtualization_vm.go
  netbox/util.go
Labels: enhancement

#157 chore(release): 5.2.0
  CHANGELOG.md
  package.json
Labels: chore

#158 feat: Add netbox_virtualization_vm_primary_ip resource
  examples/main.tf
  examples/resources/netbox_ipam_ip_addresses/resource.tf
  examples/resources/netbox_virtualization_vm_primary_ip/resource.tf
  netbox/provider.go
  netbox/resource_netbox_ipam_ip_addresses.go
  netbox/resource_netbox_virtualization_vm.go
  netbox/resource_netbox_virtualization_vm_primary_ip.go
  netbox/resource_netbox_virtualization_vm_primary_ip_test.go
Labels: enhancement

#167 ci: Fix go fmt command with sub-dirrectories
  .github/workflows/master.yml
Labels: ci

#168 chore(release): 5.3.0
  CHANGELOG.md
  package.json
Labels: chore

#169 fix: Workaround in ASN resource for 386 arch
  netbox/ipam/resource_netbox_ipam_asn.go
Labels: bug

#170 chore(release): 5.3.1
  CHANGELOG.md
  package.json
Labels: chore
