Repository smutel/terraform-provider-netbox, pull requests merged in 2022-04, with the labels that each got.

#100 ci: Update Github Actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  docs/index.md
Labels: ci

#99 fix: Allow setting local_context_data
  go.mod
  go.sum
  netbox/resource_netbox_virtualization_vm.go
  vendor/github.com/smutel/go-netbox/netbox/models/device.go
  vendor/github.com/smutel/go-netbox/netbox/models/device_with_config_context.go
  vendor/github.com/smutel/go-netbox/netbox/models/virtual_machine_with_config_context.go
  vendor/github.com/smutel/go-netbox/netbox/models/writable_device_with_config_context.go
  vendor/github.com/smutel/go-netbox/netbox/models/writable_virtual_machine_with_config_context.go
  vendor/modules.txt
Labels: bug

#101 ci: Enable changelog through goreleaser
  .goreleaser.yml
Labels: ci

#106 chore(release): 3.1.0
  CHANGELOG.md
  package.json
Labels: chore
